version: '3.9'

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=http://localhost/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3001:3001'
    volumes:
     - grafana_storage:/var/lib/grafana
     - grafana_custom_dashboards:/var/lib/grafana/dashboards
     - grafana_logs:/var/log/grafana 
     - ./conf/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - grafananet
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb_grafana
    # ports:
    #   - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=${DB_DBNAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
    volumes:
      - ./data/mariadb-data:/var/lib/mariadb
    networks:
      - grafananet

networks:
  grafananet:
    driver: bridge
    
volumes:  # Definição dos novos volumes
  grafana_storage:
  grafana_custom_dashboards:
  grafana_logs: